### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by AI-CHN** [yhzhu99/ehr-llm-benchmark#1]
我将你的源文件全部下载好，环境配好以及config配好之后还是无法运行，前面几个问题解决了之后现在出现
FileNotFoundError: [Errno 2] No such file or directory: 'prompts/mimic-iv/unit.json'。是还需要配置数据的JSON文件吗？

**Comment by yhzhu99** [comment]
你好，这个问题是因为仓库中缺少了数据集的医疗信息文件（包括数据集中特征的单位和参考范围信息）。
我们补充上传了相关文件，并修改了README文档。
现在可以重新clone仓库获得这些文件并运行程序。

**Comment by AI-CHN** [comment]
作者你好，你这边方便提供datasets吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhzhu99/ehr-llm-benchmark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月1日(星期天) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhu99/ehr-llm-benchmark] 无法运行 (Issue #1)





 
你好，这个问题是因为仓库中缺少了数据集的医疗信息文件（包括数据集中特征的单位和参考范围信息）。
 我们补充上传了相关文件，并修改了README文档。
 现在可以重新clone仓库获得这些文件并运行程序。
